services:
  app:
    container_name: weather-watch
    build: .
    volumes:
      - ./src:/usr/local/src
    ports:
      - "80:80"
    environment:
      API_KEY: "${API_KEY}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    entrypoint: uvicorn src.app.main:app --host 0.0.0.0 --port 80
 
  db:
    container_name: "weather-watch-appdb"
    build: ./data/
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_SCHEMA: app
    expose:
      - "8080"
    ports:
      - "8080:5432"
    restart: always
